---
- name: Init K8s Cluster on Master1 | initialize the cluster
  become: true
  shell: 'kubeadm init --pod-network-cidr=10.244.0.0/16 --control-plane-endpoint {{ hostvars["master1"].ansible_host }}:6443 --upload-certs >> cluster_initialized.txt'
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: Init K8s Cluster on Master1 | create .kube directory
  become: true
  become_user: ettorefoti
  file:
    path: $HOME/.kube
    state: directory

- name: Init K8s Cluster on Master1 | copy admin.conf to user's kube config
  become: true
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ettorefoti/.kube/config #TODO add exchange for local pc kubeconfig exchange
    remote_src: true
    owner: ettorefoti
    mode: 0664

- name: Init K8s Cluster on Master1 | install Pod network
  become: true
  become_user: ettorefoti
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt"
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

- name: Init K8s Cluster on Master1 | Restart kubelet #TODO move to handler all istances
  become: true
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet