---
# tasks file for setup_cluster
- name: init k8s cluster and generate join command
  hosts: master1
  become: yes
  gather_facts: false
  tasks:
    - name: kubeadm init
      import_tasks: tasks/kubeadmInitOnControlPlane.yaml
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: join workers
  hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['master1'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
    - name: Restart kubelet
      become: yes
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet