---
# tasks file for setup_cluster
- name: Setup Cluster | Init K8s Cluster on Master1
  import_tasks: kubeadmInitOnControlPlane.yml
  when: "'master1' in inventory_hostname"
- name: Setup Cluster | Join Additional Nodes
  import_tasks: join_additional_nodes.yml

