---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: parallels
  provision: true
  default_box: 'jeffnoxon/ubuntu-20.04-arm64'
lint: |
  set -e ansible-lint
platforms:
  - name: Ubuntu-2004-LTS
    box: 'jeffnoxon/ubuntu-20.04-arm64'
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    instance_raw_config_args:
      - 'vm.synced_folder ".", "/vagrant", type: "rsync"'
      - 'vm.provision :shell, inline: "uname"'
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: 'vagrant'
      synced_folder: true
provisioner:
  name: ansible
verifier:
  name: ansible
