---
 dependency:
   name: galaxy
 driver:
   name: vagrant
   provider:
      name: libvirt
 lint: |
   set -e ansible-lint
 platforms:
   - name: Ubuntu-2004-LTS
     box: ${TESTBOX:-jeffnoxon/ubuntu-20.04-arm64}
 provisioner:
   name: ansible
 verifier:
   name: ansible