---
- name: 'Initial VMs Setup | Enable BR Netfilter module'
  become: true
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: 'Initial VMs Setup | Update Kernel Settings'
  become: true
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: 'Initial VMs Setup | Remove swapfile from /etc/fstab'
  mount:
    name: '{{ item }}'
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: 'Initial VMs Setup | Disable Swap'
  command: swapoff -a

- name: 'Initial VMs Setup | Open port from ufw'
  become: true
  with_items:
    - "6443"
    - "2379"
    - "2380"
    - "10250"
    - "10259"
    - "10257"
    - "10248"
    - "8080"
  community.general.ufw:
    rule: allow
    port: '{{ item }}'