---
- name: 'Initial VMs Setup | Install Initial Required Packages'
  apt:
    name: '{{ item }}'
    state: present
    update_cache: true
  with_items: '{{ required_packages }}'

- name: 'Initial VMs Setup | Create Docker config directory'
  file:
    path: '{{ docker.config_path | default("/etc/docker")}}'
    state: directory

- name: 'Initial VMs Setup | Changing Docker to systemd driver'
  copy:
    dest: '{{ docker.config_path | default("/etc/docker")}}/daemon.json'
    content: |
      {
      "exec-opts": ["native.cgroupdriver=systemd"]
      }

- name: 'Initial VMs Setup | Install Required GPG Keys for Docker'
  become: true
  apt_key:
    url: '{{ item }}'
    state: present
  with_items: '{{ gpg_keys }}'

- name: 'Initial VMs Setup | Add APT Repository for Docker Stable Version'
  become: true
  apt_repository:
    repo: '{{ docker.repo_url }}'
    state: present

- name: 'Initial VMs Setup | Add Kubernetes Repository'
  become: true
  apt_repository:
    repo: '{{ kubernetes.repo_url }}'
    state: present
    filename: kubernetes.list

- name: 'Initial VMs Setup | Install Docker Required Packages'
  apt:
    name: '{{ item }}'
    state: present
    update_cache: true
  with_items: '{{ docker.required_packages }}'

- name: 'Initial VMs Setup | Install Kubernetes Required Packages'
  apt:
    name: '{{ item }}'
    state: present
    update_cache: true
  with_items: '{{ kubernetes.required_packages }}'

- name: 'Initial VMs Setup | APT Mark Hold Kubernetes Packages'
  become: true
  with_items:
    - kubeadm
    - kubelet
    - kubectl
  command: "apt-mark hold {{ item }}"
