---
- name: 'Initial VMs Setup | Create Docker config directory'
  file:
    path: '{{ docker.config_path | default("/etc/docker")}}'
    state: directory

- name: 'Initial VMs Setup | Changing Docker to systemd driver'
  copy:
    dest: "/etc/docker/daemon.json"
    content: |
      {
      "exec-opts": ["native.cgroupdriver=systemd"]
      }

- name: 'Initial VMs Setup | Install Required GPG Keys for Docker'
  become: true
  apt_key:
    url: '{{ item }}'
    state: present
  with_items: '{{ gpg_keys }}'

- name: 'Initial VMs Setup | Add APT Repository for Stable Version'
  become: true
  apt_repository:
    repo: '{{ docker.repo_url }}'
    state: present

- name: "Initial VMs Setup | Add Kubernetes Repository"
  become: true
  apt_repository:
    repo: '{{ kubernetes_repo_url }}'
    state: present
    filename: kubernetes.list

  - name: "Initial VMs Setup | Install All Required Packages"
    with_items:
      - ca-certificates
      - apt-transport-https
      - curl
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - kubeadm
      - kubectl
      - kubelet
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes

  - name: "Initial VMs Setup | APT Mark Hold Kubernetes Packages"
    become: yes
    with_items:
      - kubeadm
      - kubelet
      - kubectl
    command: "apt-mark hold {{ item }}"
