---
 dependency:
   name: galaxy
 driver:
   name: vagrant
   provider:
      name: parallels
 lint: |
   set -e ansible-lint
 platforms:
   - name: master1
     box: ${TESTBOX:-jeffnoxon/ubuntu-20.04-arm64}
     memory: 1800
     groups:
      - masters
     interfaces:
     - network_name: private_network
       ip: 192.168.56.2
   - name: worker1
     box: ${TESTBOX:-jeffnoxon/ubuntu-20.04-arm64}
     memory: 1800
     groups:
      - workers
     interfaces:
     - network_name: private_network
       ip: 192.168.56.3
   - name: hybrid1
     box: ${TESTBOX:-jeffnoxon/ubuntu-20.04-arm64}
     memory: 1800
     groups:
      - hybrids
     interfaces:
       - network_name: private_network
         ip: 192.168.56.4
 provisioner:
   name: ansible
 verifier:
   name: ansible